import 'package:logger/logger.dart';

class Food {
  final String name;
  bool isSelected;
  final String category;

  Food(this.name, this.isSelected, this.category);
}

void main() {
  foods.sort((a, b) {
    final categoryComparison = a.category.compareTo(b.category);
    if (categoryComparison != 0) {
      return categoryComparison;
    }
    return a.name.compareTo(b.name);
  });

  var logger = Logger();

  String currentCategory = '';

  for (var food in foods) {
    if (food.category != currentCategory) {
      logger.d('Category: ${food.category}');
      currentCategory = food.category;
    }
    logger.d(food.name);
  }
}

List<Food> foods = [
  Food('active dry yeast', false, 'Baking'),
  Food('almonds', false, 'Nuts and Seeds'),
  Food('almond extract', false, 'Flavorings'),
  Food('almond milk', false, 'Dairy'),
  Food('ancho chile', false, 'Spices'),
  Food('ancho chilis', false, 'Spices'),
  Food('anchovies', false, 'Seafood'),
  Food('anchovy', false, 'Seafood'),
  Food('anchovy fillets', false, 'Seafood'),
  Food('angel hair', false, 'Pasta'),
  Food('apple', false, 'Fruits'),
  Food('apple cider', false, 'Beverages'),
  Food('apple cider vinegar', false, 'Condiments'),
  Food('arborio', false, 'Grains'),
  Food('arrowroot', false, 'Baking'),
  Food('artichoke', false, 'Vegetables'),
  Food('artichoke hearts', false, 'Vegetables'),
  Food('artichokes', false, 'Vegetables'),
  Food('arugula', false, 'Vegetables'),
  Food('asiago cheese', false, 'Cheese'),
  Food('asian pear', false, 'Fruits'),
  Food('asparagus', false, 'Vegetables'),
  Food('avocado', false, 'Fruits'),
  Food('baby arugula', false, 'Vegetables'),
  Food('baby bok choy', false, 'Vegetables'),
  Food('baby carrots', false, 'Vegetables'),
  Food('baby kale', false, 'Vegetables'),
  Food('baby spinach', false, 'Vegetables'),
  Food('baby spinach leaves', false, 'Vegetables'),
  Food('bacon', false, 'Meats'),
  Food('bagel', false, 'Bread'),
  Food('bagel chips', false, 'Bread'),
  Food('baguette', false, 'Bread'),
  Food('baking powder', false, 'Baking'),
  Food('balsamic', false, 'Condiments'),
  Food('banana chips', false, 'Fruits'),
  Food('barley', false, 'Grains'),
  Food('bartlett', false, 'Fruits'),
  Food('basil', false, 'Herbs'),
  Food('basil cashew', false, 'Nuts and Seeds'),
  Food('basil leaves', false, 'Herbs'),
  Food('basil pesto', false, 'Condiments'),
  Food('basmati', false, 'Rice'),
  Food('bay', false, 'Spices'),
  Food('bean', false, 'Legumes'),
  Food('beans', false, 'Legumes'),
  Food('beef', false, 'Meats'),
  Food('beef chuck', false, 'Meats'),
  Food('beef short ribs', false, 'Meats'),
  Food('beef stock', false, 'Meats'),
  Food('beer', false, 'Alcohol'),
  Food('beet', false, 'Vegetables'),
  Food('bell peppers', false, 'Vegetables'),
  Food('berries', false, 'Fruits'),
  Food('best quality olive', false, 'Olives'),
  Food('bitter almond', false, 'Nuts and Seeds'),
  Food('bittersweet chocolate', false, 'Chocolate'),
  Food('black beans', false, 'Legumes'),
  Food('black olives', false, 'Olives'),
  Food('black pepper', false, 'Condiments'),
  Food('black peppercorns', false, 'Condiments'),
  Food('black sesame seeds', false, 'Nuts and Seeds'),
  Food('block mozzarella', false, 'Cheese'),
  Food('blocks tofu', false, 'Tofu'),
  Food('blood orange juice', false, 'Beverages'),
  Food('blood orange liqueur', false, 'Alcohol'),
  Food('boiling potatoes', false, 'Vegetables'),
  Food('bosc pears', false, 'Fruits'),
  Food('bourbon', false, 'Alcohol'),
  Food('boursin', false, 'Cheese'),
  Food('boursin garlic herb', false, 'Cheese'),
  Food('box frozen artichoke hearts', false, 'Frozen Foods'),
  Food('brandy', false, 'Alcohol'),
  Food('bread', false, 'Bread'),
  Food('bread crumbs', false, 'Baking'),
  Food('bread flour', false, 'Flour and Starches'),
  Food('breakfast radishes', false, 'Vegetables'),
  Food('brie cheese', false, 'Cheese'),
  Food('brioche', false, 'Bread'),
  Food('broccoli', false, 'Vegetables'),
  Food('broccoli florets', false, 'Vegetables'),
  Food('brown mustard', false, 'Condiments'),
  Food('brown rice', false, 'Rice'),
  Food('brown sugar', false, 'Sugar'),
  Food('brussels sprouts', false, 'Vegetables'),
  Food('bulghur', false, 'Grains'),
  Food('bunches broccoli', false, 'Vegetables'),
  Food('bunches kale', false, 'Vegetables'),
  Food('burger buns', false, 'Bread'),
  Food('butter', false, 'Dairy'),
  Food('buttermilk', false, 'Dairy'),
  Food('buttermilk powder', false, 'Dairy'),
  Food('butternut', false, 'Vegetables'),
  Food('butternut squash', false, 'Vegetables'),
  Food('butterscotch', false, 'Flavorings'),
  Food('cabbage', false, 'Vegetables'),
  Food('cajun spice blend', false, 'Spices'),
  Food('cake flour', false, 'Flour and Starches'),
  Food('calabrian chile paste', false, 'Condiments'),
  Food('calabrian chili paste', false, 'Condiments'),
  Food('calzone spice blend', false, 'Spices'),
  Food('cane syrup', false, 'Sweeteners'),
  Food('cannellini beans', false, 'Legumes'),
  Food('canola oil', false, 'Condiments'),
  Food('cans peas', false, 'Canned Goods'),
  Food('cans petite tomatoes with green', false, 'Canned Goods'),
  Food('cans san marzano tomatoes', false, 'Canned Goods'),
  Food('cans tomatoes', false, 'Canned Goods'),
  Food('capers', false, 'Condiments'),
  Food('caraway', false, 'Spices'),
  Food('carnaroli', false, 'Grains'),
  Food('carrot', false, 'Vegetables'),
  Food('carrots', false, 'Vegetables'),
  Food('cashews', false, 'Nuts and Seeds'),
  Food('castelvatrano', false, 'Olives'),
  Food('castelvetrano olives', false, 'Olives'),
  Food('caster', false, 'Sweeteners'),
  Food('catfish fillets', false, 'Seafood'),
  Food('cauliflower', false, 'Vegetables'),
  Food('cavatelli', false, 'Pasta'),
  Food('cayenne', false, 'Spices'),
  Food('cayenne pepper', false, 'Vegetables'),
  Food('celeriac', false, 'Vegetables'),
  Food('celery ribs', false, 'Vegetables'),
  Food('celery root', false, 'Vegetables'),
  Food('celery stalk', false, 'Vegetables'),
  Food('celery stalks', false, 'Vegetables'),
  Food('chambord', false, 'Alcohol'),
  Food('cheddar', false, 'Cheese'),
  Food('cherries', false, 'Fruits'),
  Food('cherry preserves', false, 'Condiments'),
  Food('cherry tomatoes', false, 'Vegetables'),
  Food('chervil', false, 'Herbs'),
  Food('chestnut puree', false, 'Nuts and Seeds'),
  Food('chia', false, 'Nuts and Seeds'),
  Food('chicken', false, 'Meats'),
  Food('chicken broth', false, 'Broth'),
  Food('chicken stock', false, 'Broth'),
  Food('chickpeas', false, 'Legumes'),
  Food('chikuwa', false, 'Seafood'),
  Food('chili', false, 'Spices'),
  Food('chili powder', false, 'Spices'),
  Food('chili sauce', false, 'Condiments'),
  Food('chipotle', false, 'Spices'),
  Food('chipotle chile', false, 'Spices'),
  Food('chipotle chile paste', false, 'Condiments'),
  Food('chipotle chili', false, 'Spices'),
  Food('chipotle hot sauce', false, 'Condiments'),
  Food('chipotle in', false, 'Canned Goods'),
  Food('chipotle in adobo', false, 'Canned Goods'),
  Food('chives', false, 'Herbs'),
  Food('chocolate', false, 'Chocolate'),
  Food('chocolate almond', false, 'Chocolate'),
  Food('chocolate angel food cake', false, 'Desserts'),
  Food('chocolate chips', false, 'Chocolate'),
  Food('chocolate graham crackers', false, 'Bread'),
  Food('chocolate hazelnut', false, 'Chocolate'),
  Food('chocolate malt balls', false, 'Baking'),
  Food('chocolate wafer', false, 'Chocolate'),
  Food('chunky', false, 'Sauces'),
  Food('ciabatta bread', false, 'Bread'),
  Food('ciabatta rolls', false, 'Bread'),
  Food('cilantro', false, 'Herbs'),
  Food('cilantro leaves', false, 'Herbs'),
  Food('cinnamon', false, 'Spices'),
  Food('cinnamon sticks', false, 'Spices'),
  Food('cinnamon sugar', false, 'Sugar'),
  Food('clove', false, 'Spices'),
  Food('clove black garlic', false, 'Spices'),
  Food('clove garlic', false, 'Spices'),
  Food('cloves', false, 'Spices'),
  Food('coarse', false, 'Salt'),
  Food('coarse salt', false, 'Salt'),
  Food('coarse white sparkling sugar', false, 'Sugar'),
  Food('cocoa', false, 'Baking'),
  Food('cocoa powder', false, 'Baking'),
  Food('coconut', false, 'Nuts and Seeds'),
  Food('coconut flavor', false, 'Flavorings'),
  Food('coconut milk powder', false, 'Dairy'),
  Food('coffee', false, 'Beverages'),
  Food('cold butter', false, 'Dairy'),
  Food('cold heavy cream', false, 'Cream'),
  Food('collard', false, 'Vegetables'),
  Food('confectioners', false, 'Sugar'),
  Food('container', false, 'Storage'),
  Food('containers grape', false, 'Fruits'),
  Food('cooking oil', false, 'Condiments'),
  Food('coriander', false, 'Spices'),
  Food('corn', false, 'Vegetables'),
  Food('cornichons', false, 'Condiments'),
  Food('cornmeal', false, 'Grains'),
  Food('cornstarch', false, 'Baking'),
  Food('cotija cheese', false, 'Cheese'),
  Food('country bread', false, 'Bread'),
  Food('course salt', false, 'Salt'),
  Food('crab meat', false, 'Seafood'),
  Food('crackers', false, 'Bread'),
  Food('cranberries', false, 'Fruits'),
  Food('cranberry', false, 'Fruits'),
  Food('cranberry juice blend', false, 'Beverages'),
  Food('cream cheese', false, 'Cheese'),
  Food('creamy peanut', false, 'Cream'),
  Food('creme fraiche', false, 'Dairy'),
  Food('cremini', false, 'Mushrooms'),
  Food('crusty bread', false, 'Bread'),
  Food('crusty sourdough bread', false, 'Bread'),
  Food('cucumber', false, 'Vegetables'),
  Food('cumin', false, 'Spices'),
  Food('curry', false, 'Spices'),
  Food('curry leaves', false, 'Herbs'),
  Food('daikon', false, 'Vegetables'),
  Food('dark brown sugar', false, 'Sugar'),
  Food('dark chocolate', false, 'Chocolate'),
  Food('dark cocoa', false, 'Chocolate'),
  Food('dark rum', false, 'Alcohol'),
  Food('dark sesame', false, 'Nuts and Seeds'),
  Food('dash pepper', false, 'Spices'),
  Food('dashes cayenne', false, 'Spices'),
  Food('dashi', false, 'Broth'),
  Food('dates', false, 'Fruits'),
  Food('deglet noor', false, 'Fruits'),
  Food('delicata', false, 'Vegetables'),
  Food('dijon', false, 'Condiments'),
  Food('dijon mustard', false, 'Condiments'),
  Food('dill', false, 'Herbs'),
  Food('dipping sauce', false, 'Sauces'),
  Food('dough improver', false, 'Baking'),
  Food('drops peppermint', false, 'Flavorings'),
  Food('dry great northern beans', false, 'Legumes'),
  Food('dry mustard', false, 'Spices'),
  Food('dry peanuts', false, 'Nuts and Seeds'),
  Food('dry rose', false, 'Wine'),
  Food('dry sushi', false, 'Sauces'),
  Food('dry white', false, 'Wine'),
  Food('dry white wine', false, 'Wine'),
  Food('dry wine', false, 'Wine'),
  Food('egg', false, 'Eggs'),
  Food('egg white', false, 'Eggs'),
  Food('egg whites', false, 'Eggs'),
  Food('egg yolk', false, 'Eggs'),
  Food('eggplant', false, 'Vegetables'),
  Food('eggplants', false, 'Vegetables'),
  Food('eggs cups', false, 'Eggs'),
  Food('elbow macaroni', false, 'Pasta'),
  Food('elderflower', false, 'Flavorings'),
  Food('emmenthal cheese', false, 'Cheese'),
  Food('endive', false, 'Vegetables'),
  Food('english cucumber', false, 'Vegetables'),
  Food('english muffin', false, 'Muffins'),
  Food('envelope', false, 'Storage'),
  Food('espresso', false, 'Coffee'),
  Food('espresso powder', false, 'Coffee'),
  Food('essence', false, 'Flavorings'),
  Food('extra virgin olive', false, 'Condiments'),
  Food('Bird''s eye chile pepper', false, 'Vegetables'),
  Food('fairy tale eggplant', false, 'Vegetables'),
  Food('favorite burger toppings', false, 'Condiments'),
  Food('fennel', false, 'Vegetables'),
  Food('fennel bulb', false, 'Vegetables'),
  Food('fenugreek', false, 'Spices'),
  Food('feta', false, 'Cheese'),
  Food('fig', false, 'Fruits'),
  Food('fillets', false, 'Seafood'),
  Food('fine salt', false, 'Salt'),
  Food('fine sea', false, 'Salt'),
  Food('fine semolina', false, 'Grains'),
  Food('fingerling', false, 'Potatoes'),
  Food('flakes', false, 'Spices'),
  Food('flaky sea salt', false, 'Salt'),
  Food('flatbread', false, 'Bread'),
  Food('flax', false, 'Nuts and Seeds'),
  Food('fleur de sel', false, 'Salt'),
  Food('florets frozen', false, 'Frozen Foods'),
  Food('flour', false, 'Flour and Starches'),
  Food('flour tortillas', false, 'Bread'),
  Food('fontina cheese', false, 'Cheese'),
  Food('food coloring', false, 'Condiments'),
  Food('fregola sarda', false, 'Grains'),
  Food('french baguette', false, 'Bread'),
  Food('french bread', false, 'Bread'),
  Food('fresh chives', false, 'Herbs'),
  Food('fresh dill', false, 'Herbs'),
  Food('fresh parsley', false, 'Herbs'),
  Food('fromage blanc', false, 'Cheese'),
  Food('frozen artichoke hearts', false, 'Frozen Foods'),
  Food('frozen broccoli florets', false, 'Frozen Foods'),
  Food('frozen butternut squash', false, 'Frozen Foods'),
  Food('frozen dinner', false, 'Frozen Foods'),
  Food('frozen edamame', false, 'Frozen Foods'),
  Food('frozen edamame beans', false, 'Frozen Foods'),
  Food('frozen green', false, 'Frozen Foods'),
  Food('frozen green peas', false, 'Frozen Foods'),
  Food('frozen peas', false, 'Frozen Foods'),
  Food('frozen shrimp', false, 'Frozen Foods'),
  Food('frozen spinach', false, 'Frozen Foods'),
  Food('frozen vegetable', false, 'Frozen Foods'),
  Food('frozen veggie', false, 'Frozen Foods'),
  Food('furikake', false, 'Condiments'),
  Food('gala apples', false, 'Fruits'),
  Food('garam', false, 'Spices'),
  Food('garlic', false, 'Spices'),
  Food('garlic clove', false, 'Spices'),
  Food('garlic cloves', false, 'Spices'),
  Food('garlic powder', false, 'Spices'),
  Food('garlic salt', false, 'Spices'),
  Food('garnish', false, 'Garnishes'),
  Food('gemelli', false, 'Pasta'),
  Food('generous dash ground cumin', false, 'Spices'),
  Food('ghirardelli cacao bittersweet chocolate', false, 'Chocolate'),
  Food('ghirardelli chocolate', false, 'Chocolate'),
  Food('giardiniera', false, 'Condiments'),
  Food('ginger', false, 'Spices'),
  Food('glazing sugar', false, 'Sugar'),
  Food('goat cheese', false, 'Cheese'),
  Food('goat horn peppers', false, 'Vegetables'),
  Food('godiva dark chocolate', false, 'Chocolate'),
  Food('golden mountain', false, 'Condiments'),
  Food('golden potatoes', false, 'Potatoes'),
  Food('golden syrup', false, 'Sweeteners'),
  Food('gouda cheese', false, 'Cheese'),
  Food('graham crackers', false, 'Bread'),
  Food('grainy mustard', false, 'Condiments'),
  Food('granny smith apples', false, 'Fruits'),
  Food('granola', false, 'Cereals'),
  Food('grape', false, 'Fruits'),
  Food('grape tomatoes', false, 'Vegetables'),
  Food('great northern beans', false, 'Legumes'),
  Food('greek yogurt', false, 'Dairy'),
  Food('green apple', false, 'Fruits'),
  Food('green beans', false, 'Vegetables'),
  Food('green bell pepper', false, 'Vegetables'),
  Food('green cabbage', false, 'Vegetables'),
  Food('green chili peppers', false, 'Vegetables'),
  Food('green chilies', false, 'Vegetables'),
  Food('green lentils', false, 'Legumes'),
  Food('green olives', false, 'Olives'),
  Food('green onion', false, 'Vegetables'),
  Food('green onions', false, 'Vegetables'),
  Food('green peas', false, 'Vegetables'),
  Food('green sanding sugar', false, 'Sugar'),
  Food('greens salad blend', false, 'Vegetables'),
  Food('grinds black', false, 'Condiments'),
  Food('ground black', false, 'Condiments'),
  Food('ground black pepper', false, 'Condiments'),
  Food('ground cayenne', false, 'Spices'),
  Food('ground cinnamon', false, 'Spices'),
  Food('ground cinnamon for', false, 'Spices'),
  Food('ground flax', false, 'Nuts and Seeds'),
  Food('ground pepper', false, 'Condiments'),
  Food('ground white', false, 'Condiments'),
  Food('gruyere', false, 'Cheese'),
  Food('guacamole', false, 'Sauces'),
  Food('gyoza', false, 'Frozen Foods'),
  Food('halloumi', false, 'Cheese'),
  Food('hamburger', false, 'Meats'),
  Food('hamburger buns', false, 'Bread'),
  Food('handful baby spinach', false, 'Vegetables'),
  Food('handful cilantro', false, 'Herbs'),
  Food('hanpen', false, 'Frozen Foods'),
  Food('hard eggs', false, 'Eggs'),
  Food('hard peppermint candies', false, 'Baking'),
  Food('hazelnuts', false, 'Nuts and Seeds'),
  Food('head belgian endive', false, 'Vegetables'),
  Food('head boston', false, 'Vegetables'),
  Food('head boston lettuce', false, 'Vegetables'),
  Food('head broccoli', false, 'Vegetables'),
  Food('head butter lettuce', false, 'Vegetables'),
  Food('head cabbage', false, 'Vegetables'),
  Food('head cauliflower', false, 'Vegetables'),
  Food('head escarole', false, 'Vegetables'),
  Food('head garlic', false, 'Spices'),
  Food('head radicchio', false, 'Vegetables'),
  Food('head romaine lettuce', false, 'Vegetables'),
  Food('heavy whipping cream', false, 'Cream'),
  Food('hemp', false, 'Nuts and Seeds'),
  Food('hoagie rolls', false, 'Bread'),
  Food('hoisin', false, 'Sauces'),
  Food('hoisin sauce', false, 'Sauces'),
  Food('homemade croutons', false, 'Bread'),
  Food('homemade ranch dressing mix', false, 'Condiments'),
  Food('honey', false, 'Sweeteners'),
  Food('honeycrisp apple', false, 'Fruits'),
  Food('hot chili', false, 'Sauces'),
  Food('hot mustard', false, 'Condiments'),
  Food('hot pepper', false, 'Sauces'),
  Food('hot sauce', false, 'Condiments'),
  Food('hot water', false, 'Beverages'),
  Food('hot wheat cereal', false, 'Grains'),
  Food('hummus', false, 'Sauces'),
  Food('ice', false, 'Beverages'),
  Food('ice water', false, 'Beverages'),
  Food('iceberg lettuce', false, 'Vegetables'),
  Food('idaho', false, 'Vegetables'),
  Food('imitation crab', false, 'Seafood'),
  Food('inch ginger root', false, 'Spices'),
  Food('inch long piece ginger', false, 'Spices'),
  Food('inches daikon radish', false, 'Vegetables'),
  Food('inner stalk celery', false, 'Vegetables'),
  Food('instant', false, 'Flavorings'),
  Food('instant espresso', false, 'Coffee'),
  Food('instant miso packet', false, 'Soup Mix'),
  Food('irish cream', false, 'Cream'),
  Food('italian bread', false, 'Bread'),
  Food('italian herb mix', false, 'Spices'),
  Food('italian rice', false, 'Grains'),
  Food('italian seasoning', false, 'Spices'),
  Food('jalapeno pepper', false, 'Vegetables'),
  Food('jamaican', false, 'Spices'),
  Food('japanese eggplant', false, 'Japanese'),
  Food('japanese powder', false, 'Japanese'),
  Food('japanese short grain', false, 'Japanese'),
  Food('jasmine rice', false, 'Rice'),
  Food('kalamata olives', false, 'Olives'),
  Food('kale', false, 'Vegetables'),
  Food('kewpie mayonnaise', false, 'Condiments'),
  Food('kidney beans', false, 'Legumes'),
  Food('king arthur flour', false, 'Flour and Starches'),
  Food('king arthur white wheat', false, 'Flour and Starches'),
  Food('kirschwasser', false, 'Alcohol'),
  Food('kobucha squash', false, 'Vegetables'),
  Food('konnyaku', false, 'Noodles'),
  Food('korean rice', false, 'Rice'),
  Food('kosher', false, 'Salt'),
  Food('kosher dill relish', false, 'Condiments'),
  Food('kosher salt', false, 'Salt'),
  Food('lacinato kale', false, 'Vegetables'),
  Food('lasagna noodles', false, 'Pasta'),
  Food('lavender essence', false, 'Spices'),
  Food('lavender flowers', false, 'Herbs'),
  Food('leaves green leaf', false, 'Vegetables'),
  Food('leaves romaine', false, 'Vegetables'),
  Food('leeks', false, 'Vegetables'),
  Food('lemon for garnish', false, 'Fruits'),
  Food('lemon juice', false, 'Fruits'),
  Food('lemon wedges', false, 'Fruits'),
  Food('lemon zest', false, 'Fruits'),
  Food('lemons', false, 'Fruits'),
  Food('length carrot', false, 'Vegetables'),
  Food('length english cucumber', false, 'Vegetables'),
  Food('lentils', false, 'Legumes'),
  Food('lettuce', false, 'Vegetables'),
  Food('light agave syrup', false, 'Sweeteners'),
  Food('light brown sugar', false, 'Sugar'),
  Food('light canola oil', false, 'Condiments'),
  Food('light corn syrup', false, 'Sweeteners'),
  Food('lime', false, 'Fruits'),
  Food('lime juice', false, 'Fruits'),
  Food('lime slices', false, 'Fruits'),
  Food('lime wedges', false, 'Fruits'),
  Food('lime zest', false, 'Fruits'),
  Food('liqueur', false, 'Beverages'),
  Food('lite coconut milk', false, 'Dairy'),
  Food('lite soy', false, 'Sauces'),
  Food('loaf italian bread', false, 'Bread'),
  Food('log goat', false, 'Dairy'),
  Food('long grain white', false, 'Grains'),
  Food('manchego cheese', false, 'Cheese'),
  Food('maple syrup', false, 'Sweeteners'),
  Food('maraschino', false, 'Fruits'),
  Food('marcona almonds', false, 'Nuts and Seeds'),
  Food('marinara sauce', false, 'Sauces'),
  Food('marjoram leaves', false, 'Herbs'),
  Food('mascarpone', false, 'Dairy'),
  Food('matzo', false, 'Grains'),
  Food('mayonnaise', false, 'Condiments'),
  Food('meat', false, 'Meats'),
  Food('medjool dates', false, 'Fruits'),
  Food('merckens bittersweet chocolate bar', false, 'Chocolate'),
  Food('merckens white chocolate bar', false, 'Chocolate'),
  Food('mesquite flour', false, 'Flour and Starches'),
  Food('mexican oregano', false, 'Mexican'),
  Food('mexican spice', false, 'Mexican'),
  Food('milk', false, 'Dairy'),
  Food('milk bread', false, 'Bread'),
  Food('milk chocolate', false, 'Chocolate'),
  Food('milk ricotta', false, 'Dairy'),
  Food('millet', false, 'Grains'),
  Food('mini burger', false, 'Meats'),
  Food('mint', false, 'Herbs'),
  Food('mint flavoring', false, 'Herbs'),
  Food('mirin', false, 'Condiments'),
  Food('miso', false, 'Condiments'),
  Food('molasses', false, 'Sweeteners'),
  Food('monterey jack cheese', false, 'Cheese'),
  Food('mozzarella', false, 'Cheese'),
  Food('mozzarella ball', false, 'Cheese'),
  Food('mozzarella cheese', false, 'Cheese'),
  Food('muenster cheese', false, 'Cheese'),
  Food('mushrooms', false, 'Mushrooms'),
  Food('mustard', false, 'Condiments'),
  Food('mustard powder', false, 'Spices'),
  Food('napa cabbage', false, 'Vegetables'),
  Food('navel orange', false, 'Fruits'),
  Food('navy beans', false, 'Legumes'),
  Food('nectarines', false, 'Fruits'),
  Food('neufchatel cheese', false, 'Cheese'),
  Food('nocello', false, 'Beverages'),
  Food('nonfat plain greek', false, 'Dairy'),
  Food('nonfat plain greek yogurt', false, 'Dairy'),
  Food('noodle', false, 'Noodles'),
  Food('nori', false, 'Seafood'),
  Food('nut', false, 'Nuts and Seeds '),
  Food('nutmeg', false, 'Spices'),
  Food('nuts', false, 'Nuts and Seeds'),
  Food('oats', false, 'Grains'),
  Food('oil', false, 'Condiments'),
  Food('oil from the tomato', false, 'Condiments'),
  Food('oil sun tomatoes', false, 'Condiments'),
  Food('olive', false, 'Vegetables'),
  Food('olive oil', false, 'Condiments'),
  Food('onion', false, 'Vegetables'),
  Food('onion powder', false, 'Spices'),
  Food('onions', false, 'Vegetables'),
  Food('orange', false, 'Fruits'),
  Food('orange juice', false, 'Beverages'),
  Food('orange zest', false, 'Fruits'),
  Food('oranges', false, 'Fruits'),
  Food('orecchiette', false, 'Pasta'),
  Food('oregano', false, 'Herbs'),
  Food('orzo', false, 'Pasta'),
  Food('ounces mozzarella', false, 'Dairy'),
  Food('ounces queso', false, 'Dairy'),
  Food('ounces white cheddar', false, 'Dairy'),
  Food('oyster mushrooms', false, 'Mushrooms'),
  Food('package boursin', false, 'Dairy'),
  Food('package frozen puff pastry sheets', false, 'Frozen Foods'),
  Food('package pita', false, 'Bread'),
  Food('package rapid rise yeast', false, 'Baking'),
  Food('package tofu', false, 'Soy Products'),
  Food('packages bar cream cheese', false, 'Cheese'),
  Food('packet active dry', false, 'Baking'),
  Food('packet hondashi', false, 'Seasonings'),
  Food('pancetta', false, 'Meats'),
  Food('paneer', false, 'Cheese'),
  Food('panko', false, 'Bread Crumbs'),
  Food('panko bread', false, 'Bread Crumbs'),
  Food('panko breadcrumbs', false, 'Bread Crumbs'),
  Food('paprika', false, 'Spices'),
  Food('parmesan', false, 'Dairy'),
  Food('parmesan cheese', false, 'Cheese'),
  Food('parsley', false, 'Herbs'),
  Food('parsley leaves', false, 'Herbs'),
  Food('parsnip', false, 'Vegetables'),
  Food('parsnips', false, 'Vegetables'),
  Food('pasta', false, 'Pasta'),
  Food('pastry flour', false, 'Flour and Starches'),
  Food('pastry leaves for garnish', false, 'Baking'),
  Food('pea pods', false, 'Vegetables'),
  Food('peach', false, 'Fruits'),
  Food('peanut', false, 'Nuts and Seeds'),
  Food('peanut butter', false, 'Nuts and Seeds'),
  Food('pear', false, 'Fruits'),
  Food('pears', false, 'Fruits'),
  Food('peas', false, 'Vegetables'),
  Food('pecans', false, 'Nuts and Seeds'),
  Food('pecorino romano cheese', false, 'Cheese'),
  Food('penne', false, 'Pasta'),
  Food('penne rigate', false, 'Pasta'),
  Food('pepitas', false, 'Nuts and Seeds'),
  Food('peppadew peppers', false, 'Vegetables'),
  Food('pepper', false, 'Spices'),
  Food('pepper flakes', false, 'Spices'),
  Food('pepper jack cheese', false, 'Cheese'),
  Food('peppermint crunch', false, 'Desserts'),
  Food('peppermint oil', false, 'Condiments'),
  Food('peperoncini', false, 'Vegetables'),
  Food('peppers', false, 'Vegetables'),
  Food('persian cucumbers', false, 'Vegetables'),
  Food('persimmon', false, 'Fruits'),
  Food('peruvian peppers', false, 'Vegetables'),
  Food('pesto', false, 'Sauces'),
  Food('pickles', false, 'Vegetables'),
  Food('pico de gallo', false, 'Sauces'),
  Food('pie crust', false, 'Baking'),
  Food('pie shell', false, 'Baking'),
  Food('piece ginger', false, 'Spices'),
  Food('piece lemon rind', false, 'Fruits'),
  Food('pieces leftover bonchon chicken', false, 'Leftovers'),
  Food('pieces naan bread', false, 'Bread'),
  Food('pieces pita', false, 'Bread'),
  Food('pinch cayenne', false, 'Spices'),
  Food('pinch ground white', false, 'Spices'),
  Food('pinch kosher', false, 'Salt'),
  Food('pinch pepper', false, 'Spices'),
  Food('pinch sea', false, 'Salt'),
  Food('pinch sea salt', false, 'Salt'),
  Food('pine nuts', false, 'Nuts and Seeds'),
  Food('pineapple', false, 'Fruits'),
  Food('pint chocolate ice', false, 'Desserts'),
  Food('pint grape', false, 'Fruits'),
  Food('pint grape tomatoes', false, 'Vegetables'),
  Food('pint vanilla ice', false, 'Desserts'),
  Food('pinto beans', false, 'Legumes'),
  Food('piquillo', false, 'Vegetables'),
  Food('piquillo peppers', false, 'Vegetables'),
  Food('pistachios', false, 'Nuts and Seeds'),
  Food('pita', false, 'Bread'),
  Food('pitas', false, 'Bread'),
  Food('pizza', false, 'Pizza'),
  Food('pizza dough', false, 'Pizza'),
  Food('pizza dough flavor', false, 'Pizza'),
  Food('pkg frozen winter squash', false, 'Frozen Foods'),
  Food('plain dry bread crumbs', false, 'Bread Crumbs'),
  Food('plain greek', false, 'Dairy'),
  Food('plain nonfat greek', false, 'Dairy'),
  Food('plain pizza', false, 'Pizza'),
  Food('plain yogurt', false, 'Dairy'),
  Food('plantain', false, 'Fruits'),
  Food('plum tomato', false, 'Vegetables'),
  Food('plum tomatoes', false, 'Vegetables'),
  Food('plums', false, 'Fruits'),
  Food('plus turbinando sugar', false, 'Sugar'),
  Food('poblano chile', false, 'Vegetables'),
  Food('poblano chili peppers', false, 'Vegetables'),
  Food('poblano pepper', false, 'Vegetables'),
  Food('poblano peppers', false, 'Vegetables'),
  Food('ponzu', false, 'Sauces'),
  Food('porcini', false, 'Mushrooms'),
  Food('pork', false, 'Meats'),
  Food('portobello mushroom caps', false, 'Mushrooms'),
  Food('portobello mushrooms', false, 'Mushrooms'),
  Food('potato gnocchi', false, 'Pasta'),
  Food('potato starch', false, 'Flour and Starches'),
  Food('potato starch powder', false, 'Flour and Starches'),
  Food('potatoes', false, 'Vegetables'),
  Food('prosciutto', false, 'Meats'),
  Food('provolone cheese', false, 'Cheese'),
  Food('prunes', false, 'Dried Fruits'),
  Food('pumpkin', false, 'Vegetables'),
  Food('pumpkin pie', false, 'Desserts'),
  Food('pumpkin puree', false, 'Canned Goods'),
  Food('pumpkin seeds', false, 'Nuts and Seeds'),
  Food('pure pumpkin', false, 'Canned Goods'),
  Food('pure vanilla', false, 'Baking'),
  Food('pure vanilla extract', false, 'Baking'),
  Food('quart vegetable', false, 'Vegetables'),
  Food('queso blanco', false, 'Cheese'),
  Food('queso fresco', false, 'Cheese'),
  Food('radishes', false, 'Vegetables'),
  Food('rainbow carrots', false, 'Vegetables'),
  Food('ranch dressing dry mix', false, 'Condiments'),
  Food('ras al', false, 'Spices'),
  Food('raspberries', false, 'Fruits'),
  Food('raspberry', false, 'Fruits'),
  Food('raspberry jam', false, 'Jams and Jellies'),
  Food('raw', false, 'Meats'),
  Food('raw green pumpkin', false, 'Vegetables'),
  Food('raw shrimp', false, 'Seafood'),
  Food('regular white', false, 'Flour and Starches'),
  Food('rice', false, 'Rice'),
  Food('rice vermicelli', false, 'Rice'),
  Food('rice vinegar', false, 'Condiments'),
  Food('rice wine', false, 'Condiments'),
  Food('rice wine vinegar', false, 'Condiments'),
  Food('ricotta', false, 'Dairy'),
  Food('ripe mango', false, 'Fruits'),
  Food('ripe plantain', false, 'Fruits'),
  Food('rolls', false, 'Bakery'),
  Food('roma tomatoes', false, 'Vegetables'),
  Food('romaine', false, 'Vegetables'),
  Food('romaine lettuce', false, 'Vegetables'),
  Food('romaine lettuce heart', false, 'Vegetables'),
  Food('romano cheese', false, 'Cheese'),
  Food('rosemary leaves', false, 'Herbs'),
  Food('rosemary oil', false, 'Condiments'),
  Food('rum flavoring', false, 'Flavorings'),
  Food('russet', false, 'Vegetables'),
  Food('russet potatoes', false, 'Vegetables'),
  Food('rustic bread', false, 'Bakery'),
  Food('safflower oil', false, 'Condiments'),
  Food('saffron', false, 'Spices'),
  Food('sage', false, 'Herbs'),
  Food('sage leaves', false, 'Herbs'),
  Food('sake', false, 'Alcohol'),
  Food('salad', false, 'Vegetables'),
  Food('salad greens', false, 'Vegetables'),
  Food('salami', false, 'Meats'),
  Food('salmon', false, 'Seafood'),
  Food('salmon filet', false, 'Seafood'),
  Food('salsa', false, 'Condiments'),
  Food('salt', false, 'Condiments'),
  Food('salt pepper', false, 'Condiments'),
  Food('sambal', false, 'Condiments'),
  Food('sanding sugar', false, 'Sugar'),
  Food('sandwich', false, 'Bakery'),
  Food('sandwich roll', false, 'Bakery'),
  Food('sauce', false, 'Condiments'),
  Food('savory tomato', false, 'Canned Goods'),
  Food('scallion greens', false, 'Vegetables'),
  Food('scallions', false, 'Vegetables'),
  Food('scallops', false, 'Seafood'),
  Food('scoop protein powder', false, 'Protein Supplements'),
  Food('sea salt', false, 'Condiments'),
  Food('seedless cucumber', false, 'Vegetables'),
  Food('seitan', false, 'Meat Substitutes'),
  Food('seltzer', false, 'Beverages'),
  Food('semisweet chocolate', false, 'Baking'),
  Food('semisweet chocolate chips', false, 'Baking'),
  Food('semisweet mini chocolate', false, 'Baking'),
  Food('semolina to coat the muffins', false, 'Flour and Starches'),
  Food('serrano chile pepper', false, 'Vegetables'),
  Food('serrano pepper', false, 'Vegetables'),
  Food('serrano peppers', false, 'Vegetables'),
  Food('sesame', false, 'Nuts and Seeds'),
  Food('sesame oil', false, 'Condiments'),
  Food('sesame salt', false, 'Condiments'),
  Food('sesame seeds', false, 'Nuts and Seeds'),
  Food('shallots', false, 'Vegetables'),
  Food('sharp cheddar', false, 'Cheese'),
  Food('sharp cheddar cheese', false, 'Cheese'),
  Food('sharp white', false, 'Cheese'),
  Food('sharp white cheddar cheese', false, 'Cheese'),
  Food('sheet', false, 'Bakery'),
  Food('sheet nori', false, 'Seafood'),
  Food('sheets frozen phyllo dough', false, 'Bakery'),
  Food('shell', false, 'Bakery'),
  Food('sherry', false, 'Alcohol'),
  Food('sherry vinegar', false, 'Condiments'),
  Food('shichimi pepper', false, 'Spices'),
  Food('shiitake mushrooms', false, 'Mushrooms'),
  Food('shishito peppers', false, 'Vegetables'),
  Food('shortening', false, 'Baking'),
  Food('shrimp', false, 'Seafood'),
  Food('sichuan chili', false, 'Spices'),
  Food('silken tofu', false, 'Tofu'),
  Food('size frozen shrimp', false, 'Seafood'),
  Food('skinless halibut fillets', false, 'Seafood'),
  Food('skinless salmon fillets', false, 'Seafood'),
  Food('skinless trout', false, 'Seafood'),
  Food('smoky cod spice blend', false, 'Spices'),
  Food('snow', false, 'Vegetables'),
  Food('snowpeas', false, 'Vegetables'),
  Food('soba noodles', false, 'Noodles'),
  Food('sodium chicken', false, 'Condiments'),
  Food('soft goat cheese', false, 'Cheese'),
  Food('soft myzithra cheese', false, 'Cheese'),
  Food('soft rolls', false, 'Bakery'),
  Food('solerno', false, 'Alcohol'),
  Food('sorghum', false, 'Grains'),
  Food('sour cream', false, 'Dairy'),
  Food('sour sauce', false, 'Condiments'),
  Food('sourdough', false, 'Bakery'),
  Food('sourdough bread', false, 'Bakery'),
  Food('sourdough bread boules', false, 'Bakery'),
  Food('southern spice', false, 'Spices'),
  Food('soy', false, 'Protein'),
  Food('soy sauce', false, 'Condiments'),
  Food('spice', false, 'Spices'),
  Food('spinach', false, 'Vegetables'),
  Food('spinach leaves', false, 'Vegetables'),
  Food('splash sherry', false, 'Alcohol'),
  Food('split green', false, 'Peas'),
  Food('sprig', false, 'Herbs'),
  Food('sprig cilantro', false, 'Herbs'),
  Food('sprig dill', false, 'Herbs'),
  Food('sprig rosemary', false, 'Herbs'),
  Food('sprig thyme', false, 'Herbs'),
  Food('sprinkles', false, 'Baking'),
  Food('squeeze lemon', false, 'Fruits'),
  Food('sriracha', false, 'Condiments'),
  Food('stack keebler club crackers', false, 'Bread'),
  Food('stalk celery', false, 'Vegetables'),
  Food('stalks celery', false, 'Vegetables'),
  Food('stick butter', false, 'Dairy'),
  Food('sticky bun', false, 'Bakery'),
  Food('stout beer', false, 'Alcohol'),
  Food('strawberries', false, 'Fruits'),
  Food('strip orange zest', false, 'Fruits'),
  Food('strips bacon', false, 'Meats'),
  Food('sugar', false, 'Sugar'),
  Food('sugar pumpkin', false, 'Sugar'),
  Food('summer squash', false, 'Vegetables'),
  Food('sunflower', false, 'Nuts and Seeds'),
  Food('super tofu', false, 'Tofu'),
  Food('superfine sugar', false, 'Sugar'),
  Food('sushi', false, 'Seafood'),
  Food('sushi rice', false, 'Rice'),
  Food('sweet chili', false, 'Condiments'),
  Food('sweet chili jam', false, 'Condiments'),
  Food('sweet miso', false, 'Condiments'),
  Food('sweet peppers', false, 'Vegetables'),
  Food('sweet piquante peppers', false, 'Vegetables'),
  Food('sweet potato', false, 'Vegetables'),
  Food('sweet potatoes', false, 'Vegetables'),
  Food('sweet potatoes cut into inch', false, 'Vegetables'),
  Food('sweet white miso', false, 'Condiments'),
  Food('swiss cheese', false, 'Cheese'),
  Food('tabasco', false, 'Condiments'),
  Food('tablespooon ground', false, 'Spices'),
  Food('taco', false, 'Mexican'),
  Food('tahini', false, 'Condiments'),
  Food('tarragon', false, 'Herbs'),
  Food('tart cherries', false, 'Fruits'),
  Food('tart green apple', false, 'Fruits'),
  Food('tempeh', false, 'Meat Substitutes'),
  Food('tempura', false, 'Japanese'),
  Food('tempura mix', false, 'Japanese'),
  Food('teriyaki sauce with', false, 'Condiments'),
  Food('thai', false, 'Asian'),
  Food('thai chili', false, 'Vegetables'),
  Food('thick bread', false, 'Bakery'),
  Food('thick crusty', false, 'Bakery'),
  Food('thick sandwich', false, 'Bakery'),
  Food('thin asparagus', false, 'Vegetables'),
  Food('thin cheddar', false, 'Cheese'),
  Food('thin crusty baguette', false, 'Bakery'),
  Food('thyme', false, 'Herbs'),
  Food('thyme leaves', false, 'Herbs'),
  Food('basil', false, 'Herbs'),
  Food('ice water', false, 'Beverages'),
  Food('lukewarm water', false, 'Beverages'),
  Food('toast', false, 'Bakery'),
  Food('tofu', false, 'Tofu'),
  Food('tofu cutlet', false, 'Tofu'),
  Food('tofu marinade', false, 'Tofu'),
  Food('tomato', false, 'Vegetables'),
  Food('tomatoes', false, 'Vegetables'),
  Food('tomatoes in juice', false, 'Canned Goods'),
  Food('tomatoes in oil', false, 'Canned Goods'),
  Food('tonkatsu sauce', false, 'Condiments'),
  Food('tortilla bowl', false, 'Mexican'),
  Food('tortillas', false, 'Mexican'),
  Food('triple', false, 'Bakery'),
  Food('truffle', false, 'Mushrooms'),
  Food('truffle oil', false, 'Condiments'),
  Food('turbinado', false, 'Sugar'),
  Food('turkish bay', false, 'Herbs'),
  Food('turnip', false, 'Vegetables'),
  Food('udon noodles', false, 'Noodles'),
  Food('vadouvan curry', false, 'Spices'),
  Food('vanilla', false, 'Baking'),
  Food('vanilla bean', false, 'Baking'),
  Food('vanilla extract', false, 'Baking'),
  Food('vanilla ice cream', false, 'Desserts'),
  Food('vanilla wafer cookies', false, 'Cookies'),
  Food('veal bones', false, 'Meats'),
  Food('vegetable broth', false, 'Condiments'),
  Food('vegetable oil', false, 'Condiments'),
  Food('vegetable shortening', false, 'Baking'),
  Food('vegetable spray', false, 'Condiments'),
  Food('vegetable stock', false, 'Condiments'),
  Food('vidalia onion', false, 'Vegetables'),
  Food('vinegar', false, 'Condiments'),
  Food('virgin coconut', false, 'Condiments'),
  Food('walnuts', false, 'Nuts and Seeds'),
  Food('wasabi', false, 'Condiments'),
  Food('wasabi paste', false, 'Condiments'),
  Food('water', false, 'Beverages'),
  Food('watercress', false, 'Vegetables'),
  Food('weeknight hero spice', false, 'Spices'),
  Food('wheat', false, 'Grains'),
  Food('whipping cream', false, 'Dairy'),
  Food('whiskey', false, 'Alcohol'),
  Food('white beans', false, 'Legumes'),
  Food('white bread flour', false, 'Flour and Starches'),
  Food('white button mushrooms', false, 'Mushrooms'),
  Food('white cheddar cheese', false, 'Cheese'),
  Food('white chocolate', false, 'Baking'),
  Food('white chocolate pieces', false, 'Baking'),
  Food('white endive', false, 'Vegetables'),
  Food('white jasmine', false, 'Rice'),
  Food('white onion', false, 'Vegetables'),
  Food('white potatoes', false, 'Vegetables'),
  Food('white rice', false, 'Rice'),
  Food('white sandwich bread', false, 'Bakery'),
  Food('white sesame seeds', false, 'Nuts and Seeds'),
  Food('white sugar', false, 'Sugar'),
  Food('white wine', false, 'Alcohol'),
  Food('wide flat rice', false, 'Rice'),
  Food('wine', false, 'Alcohol'),
  Food('wine vinegar', false, 'Condiments'),
  Food('wonton', false, 'Pasta'),
  Food('worcestershire sauce', false, 'Sauces'),
  Food('xanthan gum', false, 'Flour and Starches'),
  Food('yellow bell', false, 'Vegetables'),
  Food('yellow bell pepper', false, 'Vegetables'),
  Food('yellow cheddar cheese', false, 'Cheese'),
  Food('yellow curry', false, 'Spices'),
  Food('yellow onion', false, 'Vegetables'),
  Food('yellow onions', false, 'Vegetables'),
  Food('yellow squash', false, 'Vegetables'),
  Food('yu choy', false, 'Vegetables'),
  Food('yukon gold', false, 'Vegetables'),
  Food('yukon gold potato', false, 'Vegetables'),
  Food('yukon gold potatoes', false, 'Vegetables'),
  Food('zhong', false, 'Grains'),
  Food('ziti rigate', false, 'Pasta'),
  Food('zucchini', false, 'Vegetables'),
];