import 'package:flutter/material.dart';
import 'screen3.dart';

// Food class to represent a food with a name and an isSelected status
// indicating whether it has been selected:
class Food {
  final String name;
  bool isSelected;
  final String category;
  Food(this.name, this.isSelected, this.category);
}

// Define a controller
ScrollController _scrollController = ScrollController();

// Screen2: checklist
class Screen2 extends StatefulWidget {
  const Screen2({Key? key}) : super(key: key);
  @override
  Screen2State createState() => Screen2State();
}
// Food list
class Screen2State extends State<Screen2> {
  String filter = '';
  List<Food> filteredFoods = [];
  List<Food> selectedFoods = [];

  final TextEditingController searchController = TextEditingController();

  @override
  Widget build(BuildContext context) {

    filteredFoods = foods
        .where((food) => food.name.toLowerCase().contains(filter.toLowerCase()))
        .toList();
    filteredFoods.sort((a, b) {
      final containsA = a.name.toLowerCase() == filter.trim().toLowerCase();
      final containsB = b.name.toLowerCase() == filter.trim().toLowerCase();
      if (containsA && !containsB) {
        return -1;
      } else if (!containsA && containsB) {
        return 1;
      } else {
        return 0;
      }
    });

    return ScrollbarTheme(
      data: ScrollbarThemeData(
        thumbColor: MaterialStateProperty.all(Colors.deepOrange),
      ),
      child: Scaffold(
        backgroundColor: Colors.deepOrange[50],
        appBar: AppBar(
          backgroundColor: Colors.deepOrange,
          elevation: 0.0,
        ),
        body: Column(
          children: <Widget>[
            const Padding(
              padding: EdgeInsets.all(16.0),
              child: Text(
                'Check what you have:',
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 2,
                  color: Colors.deepOrange,
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              child: TextField(
                controller: searchController,
                style: const TextStyle(color: Colors.black),
                decoration: const InputDecoration(
                  hintText: 'Search for food',
                  hintStyle: TextStyle(color: Colors.black),
                  prefixIcon: Icon(Icons.search, color: Colors.black),
                ),
                onChanged: (value) {
                  setState(() {
                    filter = value;
                  });
                },
              ),
            ),
            Expanded(
              child: Scrollbar(
                controller: _scrollController,
                thumbVisibility: true,
                child: ListView.builder(
                  itemCount: filteredFoods.length,
                  itemBuilder: (context, index) {
                    final food = filteredFoods[index];
                    if (index == 0 || food.category != filteredFoods[index - 1].category) {
                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Text(
                              food.category,
                              style: const TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                                color: Colors.deepOrange,
                              ),
                            ),
                          ),
                          CheckboxListTile(
                            title: Text(food.name),
                            value: food.isSelected,
                            onChanged: (bool? value) {
                              setState(() {
                                food.isSelected = value ?? false;
                              });
                            },
                          ),
                        ],
                      );
                    } else {
                      return CheckboxListTile(
                        title: Text(food.name),
                        value: food.isSelected,
                        onChanged: (bool? value) {
                          setState(() {
                            food.isSelected = value ?? false;
                          });
                        },
                      );
                    }
                  },
                ),
              ),
            ),
          ElevatedButton(
            onPressed: () {
            final selectedItems = filteredFoods.where((food) => food.isSelected).toList();
            Navigator.of(context).push(
            MaterialPageRoute(
            builder: (context) => Screen3(
            foods: selectedItems,
            ),
            ),
            );
            },
          style: ButtonStyle(
          backgroundColor: MaterialStateProperty.all<Color>(Colors.deepOrange),
          ),
            child: const Text('Discover the recipes!'),
          ),
          ],
        ),
      ),
    );
  } // Build.context

  List<Food> foods = [
    Food('active dry yeast', false, 'Baking Ingredients'),
    Food('almond', false, 'Nuts and Seeds'),
    Food('almond extract', false, 'Flavorings'),
    Food('almond milk', false, 'Dairy Alternatives'),
    Food('almonds', false, 'Nuts and Seeds'),
    Food('ancho chile', false, 'Spices'),
    Food('ancho chilis', false, 'Spices'),
    Food('anchovies', false, 'Seafood'),
    Food('anchovy', false, 'Seafood'),
    Food('anchovy fillets', false, 'Seafood'),
    Food('angel hair', false, 'Pasta'),
    Food('angel hair pasta', false, 'Pasta'),
    Food('apple', false, 'Fruits'),
    Food('apple cider', false, 'Beverages'),
    Food('apple cider vinegar', false, 'Condiments'),
    Food('arborio', false, 'Grains'),
    Food('arrowroot', false, 'Baking Ingredients'),
    Food('artichoke', false, 'Vegetables'),
    Food('artichoke hearts', false, 'Vegetables'),
    Food('artichoke hearts in water', false, 'Canned Goods'),
    Food('artichokes', false, 'Vegetables'),
    Food('arugula', false, 'Greens'),
    Food('asiago cheese', false, 'Cheese'),
    Food('asian pear', false, 'Fruits'),
    Food('asparagus', false, 'Vegetables'),
    Food('avocado', false, 'Fruits'),
    Food('avocados', false, 'Fruits'),
    Food('baby arugula', false, 'Greens'),
    Food('baby bok choy', false, 'Vegetables'),
    Food('baby carrots', false, 'Vegetables'),
    Food('baby kale', false, 'Greens'),
    Food('baby spinach', false, 'Greens'),
    Food('baby spinach leaves', false, 'Greens'),
    Food('bacon', false, 'Meats'),
    Food('bagel', false, 'Bread'),
    Food('bagel chips', false, 'Snacks'),
    Food('baguette', false, 'Bread'),
    Food('baking', false, 'Baking Ingredients'),
    Food('baking powder', false, 'Baking Ingredients'),
    Food('balsamic', false, 'Condiments'),
    Food('bamboo skewers', false, 'Cooking Utensils'),
    Food('banana chips', false, 'Snacks'),
    Food('bar', false, 'Alcohol'),
    Food('barley', false, 'Grains'),
    Food('bartlett', false, 'Fruits'),
    Food('basil', false, 'Herbs'),
    Food('basil cashew', false, 'Nuts and Seeds'),
    Food('basil leaves', false, 'Herbs'),
    Food('basil pesto', false, 'Condiments'),
    Food('basmati', false, 'Rice'),
    Food('bay', false, 'Spices'),
    Food('bean', false, 'Legumes'),
    Food('beans', false, 'Legumes'),
    Food('beef', false, 'Meats'),
    Food('beef chuck', false, 'Meats'),
    Food('beef short ribs', false, 'Meats'),
    Food('beef stock', false, 'Broth'),
    Food('beer', false, 'Alcohol'),
    Food('beet', false, 'Vegetables'),
    Food('beets', false, 'Vegetables'),
    Food('bell', false, 'Peppers'),
    Food('bell peppers', false, 'Peppers'),
    Food('berries', false, 'Fruits'),
    Food('best quality olive', false, 'Olives'),
    Food('bitter almond', false, 'Nuts and Seeds'),
    Food('bittersweet', false, 'Chocolate'),
    Food('bittersweet chocolate', false, 'Chocolate'),
    Food('black bean', false, 'Legumes'),
    Food('black beans', false, 'Legumes'),
    Food('black olives', false, 'Olives'),
    Food('black pepper', false, 'Spices'),
    Food('black peppercorns', false, 'Spices'),
    Food('black sesame', false, 'Nuts and Seeds'),
    Food('black sesame seeds', false, 'Nuts and Seeds'),
    Food('block mozzarella', false, 'Cheese'),
    Food('blocks tofu', false, 'Tofu'),
    Food('blood orange juice', false, 'Beverages'),
    Food('blood orange liqueur', false, 'Alcohol'),
    Food('bocconcini', false, 'Cheese'),
    Food('boiling potatoes', false, 'Vegetables'),
    Food('boiling water', false, 'Water'),
    Food('bosc pears', false, 'Fruits'),
    Food('bourbon', false, 'Alcohol'),
    Food('boursin', false, 'Cheese'),
    Food('boursin garlic herb', false, 'Cheese'),
    Food('bowl water', false, 'Baking Ingredients'),
    Food('box frozen artichoke hearts', false, 'Frozen Foods'),
    Food('brandy', false, 'Alcohol'),
    Food('bread', false, 'Bread'),
    Food('bread crumbs', false, 'Baking Ingredients'),
    Food('bread flour', false, 'Baking Ingredients'),
    Food('breakfast radishes', false, 'Vegetables'),
    Food('brie cheese', false, 'Cheese'),
    Food('brioche', false, 'Bread'),
    Food('broccoli', false, 'Vegetables'),
    Food('broccoli florets', false, 'Vegetables'),
    Food('brown mustard', false, 'Condiments'),
    Food('brown rice', false, 'Grains'),
    Food('brown sugar', false, 'Sweeteners'),
    Food('brussels sprouts', false, 'Vegetables'),
    Food('bulghur', false, 'Grains'),
    Food('bunches broccoli', false, 'Vegetables'),
    Food('bunches kale', false, 'Greens'),
    Food('burger buns', false, 'Bread'),
    Food('butter', false, 'Dairy'),
    Food('buttermilk', false, 'Dairy'),
    Food('buttermilk powder', false, 'Dairy'),
    Food('butternut', false, 'Vegetables'),
    Food('butternut squash', false, 'Vegetables'),
    Food('butterscotch', false, 'Flavorings'),
    Food('cabbage', false, 'Vegetables'),
    Food('cajun spice blend', false, 'Spices'),
    Food('cake', false, 'Desserts'),
    Food('cake flour', false, 'Baking Ingredients'),
    Food('calabrian chile paste', false, 'Condiments'),
    Food('calabrian chili paste', false, 'Condiments'),
    Food('calzone spice blend', false, 'Spices'),
    Food('cane', false, 'Sweeteners'),
    Food('cane syrup', false, 'Sweeteners'),
    Food('cannellini beans', false, 'Legumes'),
    Food('canola', false, 'Cooking Oils'),
    Food('canola oil', false, 'Cooking Oils'),
    Food('cans peas', false, 'Canned Goods'),
    Food('cans petite tomatoes with green', false, 'Canned Goods'),
    Food('cans san marzano tomatoes', false, 'Canned Goods'),
    Food('cans tomatoes', false, 'Canned Goods'),
    Food('capers', false, 'Condiments'),
    Food('caraway', false, 'Spices'),
    Food('carnaroli', false, 'Grains'),
    Food('carrot', false, 'Vegetables'),
    Food('carrots', false, 'Vegetables'),
    Food('cashews', false, 'Nuts and Seeds'),
    Food('castelvatrano', false, 'Olives'),
    Food('castelvetrano', false, 'Olives'),
    Food('castelvetrano olives', false, 'Olives'),
    Food('caster', false, 'Sweeteners'),
    Food('catfish fillets', false, 'Seafood'),
    Food('cauliflower', false, 'Vegetables'),
    Food('cavatelli', false, 'Pasta'),
    Food('cayenne', false, 'Spices'),
    Food('cayenne pepper', false, 'Spices'),
    Food('celeriac', false, 'Vegetables'),
    Food('celery ribs', false, 'Vegetables'),
    Food('celery root', false, 'Vegetables'),
    Food('celery stalk', false, 'Vegetables'),
    Food('celery stalks', false, 'Vegetables'),
    Food('chambord', false, 'Alcohol'),
    Food('cheddar', false, 'Cheese'),
    Food('cheddar cheese', false, 'Cheese'),
    Food('cheese', false, 'Cheese'),
    Food('cherries', false, 'Fruits'),
    Food('cherry', false, 'Fruits'),
    Food('cherry preserves', false, 'Condiments'),
    Food('cherry tomatoes', false, 'Vegetables'),
    Food('chervil', false, 'Herbs'),
    Food('chestnut puree', false, 'Nuts and Seeds'),
    Food('chia', false, 'Nuts and Seeds'),
    Food('chicken', false, 'Meats'),
    Food('chicken broth', false, 'Broth'),
    Food('chicken stock', false, 'Broth'),
    Food('chickpeas', false, 'Legumes'),
    Food('chikuwa', false, 'Seafood'),
    Food('chili', false, 'Spices'),
    Food('chili powder', false, 'Spices'),
    Food('chili sauce', false, 'Condiments'),
    Food('chipotle', false, 'Spices'),
    Food('chipotle chile', false, 'Spices'),
    Food('chipotle chile paste', false, 'Condiments'),
    Food('chipotle chili', false, 'Spices'),
    Food('chipotle hot sauce', false, 'Condiments'),
    Food('chipotle in', false, 'Canned Goods'),
    Food('chipotle in adobo', false, 'Canned Goods'),
    Food('chives', false, 'Herbs'),
    Food('chocolate', false, 'Chocolate'),
    Food('chocolate almond', false, 'Chocolate'),
    Food('chocolate angel food cake', false, 'Desserts'),
    Food('chocolate chips', false, 'Chocolate'),
    Food('chocolate graham crackers', false, 'Snacks'),
    Food('chocolate hazelnut', false, 'Chocolate'),
    Food('chocolate malt balls', false, 'Candy'),
    Food('chocolate wafer', false, 'Chocolate'),
    Food('chunky', false, 'Sauces'),
    Food('ciabatta bread', false, 'Bread'),
    Food('ciabatta rolls', false, 'Bread'),
    Food('cilantro', false, 'Herbs'),
    Food('cilantro leaves', false, 'Herbs'),
    Food('cinnamon', false, 'Spices'),
    Food('cinnamon sticks', false, 'Spices'),
    Food('cinnamon sugar', false, 'Sweeteners'),
    Food('clear', false, 'Sweeteners'),
    Food('clove', false, 'Spices'),
    Food('clove black garlic', false, 'Spices'),
    Food('clove garlic', false, 'Spices'),
    Food('cloves', false, 'Spices'),
    Food('coarse', false, 'Salt'),
    Food('coarse salt', false, 'Salt'),
    Food('coarse white sparkling sugar', false, 'Sweeteners'),
    Food('cocoa', false, 'Baking Ingredients'),
    Food('cocoa powder', false, 'Baking Ingredients'),
    Food('coconut', false, 'Nuts and Seeds'),
    Food('coconut flavor', false, 'Flavorings'),
    Food('coconut milk powder', false, 'Dairy Alternatives'),
    Food('coconut one', false, 'Dairy Alternatives'),
    Food('coffee', false, 'Beverages'),
    Food('cold butter', false, 'Dairy'),
    Food('cold heavy', false, 'Dairy'),
    Food('cold heavy cream', false, 'Dairy'),
    Food('cold water to thin out', false, 'Water'),
    Food('collard', false, 'Greens'),
    Food('confectioners', false, 'Sweeteners'),
    Food('container', false, 'Storage'),
    Food('containers grape', false, 'Fruits'),
    Food('cooking', false, 'Cooking Oils'),
    Food('cooking apple', false, 'Fruits'),
    Food('cooking oil', false, 'Cooking Oils'),
    Food('coriander', false, 'Spices'),
    Food('corn', false, 'Vegetables'),
    Food('cornichons', false, 'Condiments'),
    Food('cornmeal', false, 'Grains'),
    Food('cornstarch', false, 'Baking Ingredients'),
    Food('cotija cheese', false, 'Cheese'),
    Food('country bread', false, 'Bread'),
    Food('course salt', false, 'Salt'),
    Food('crabmeat', false, 'Seafood'),
    Food('crackers', false, 'Snacks'),
    Food('cranberries', false, 'Fruits'),
    Food('cranberry', false, 'Fruits'),
    Food('cranberry juice blend', false, 'Beverages'),
    Food('cream', false, 'Dairy'),
    Food('cream cheese', false, 'Dairy'),
    Food('creamy peanut', false, 'Nuts and Seeds'),
    Food('creme', false, 'Dairy'),
    Food('creme fraiche', false, 'Dairy'),
    Food('cremini', false, 'Mushrooms'),
    Food('cremini mushrooms', false, 'Mushrooms'),
    Food('crusty', false, 'Bread'),
    Food('crusty bread', false, 'Bread'),
    Food('crusty sourdough bread', false, 'Bread'),
    Food('cucumber', false, 'Vegetables'),
    Food('cucumbers', false, 'Vegetables'),
    Food('cumin', false, 'Spices'),
    Food('cups', false, 'Cooking Utensils'),
    Food('curry', false, 'Spices'),
    Food('curry leaves', false, 'Herbs'),
    Food('daikon', false, 'Vegetables'),
    Food('daikon radish', false, 'Vegetables'),
    Food('daikon radish sprouts', false, 'Vegetables'),
    Food('dark brown', false, 'Sweeteners'),
    Food('dark brown sugar', false, 'Sweeteners'),
    Food('dark chocolate', false, 'Chocolate'),
    Food('dark cocoa', false, 'Chocolate'),
    Food('dark rum', false, 'Alcohol'),
    Food('dark sesame', false, 'Nuts and Seeds'),
    Food('dash pepper', false, 'Spices'),
    Food('dashes cayenne', false, 'Spices'),
    Food('dashi', false, 'Broth'),
    Food('dates', false, 'Fruits'),
    Food('deglet noor', false, 'Fruits'),
    Food('delicata', false, 'Vegetables'),
    Food('dijon', false, 'Condiments'),
    Food('dijon mustard', false, 'Condiments'),
    Food('dill', false, 'Herbs'),
    Food('dipping sauce', false, 'Sauces'),
    Food('dough improver', false, 'Baking Ingredients'),
    Food('drops peppermint', false, 'Flavorings'),
    Food('dry great northern beans', false, 'Legumes'),
    Food('dry mustard', false, 'Spices'),
    Food('dry peanuts', false, 'Nuts and Seeds'),
    Food('dry rose', false, 'Wine'),
    Food('dry sushi', false, 'Sauces'),
    Food('dry white', false, 'Wine'),
    Food('dry white wine', false, 'Wine'),
    Food('dry wine', false, 'Wine'),
    Food('egg', false, 'Eggs'),
    Food('egg white', false, 'Eggs'),
    Food('egg whites', false, 'Eggs'),
    Food('egg yolk', false, 'Eggs'),
    Food('egg yolks', false, 'Eggs'),
    Food('eggplant', false, 'Vegetables'),
    Food('eggplants', false, 'Vegetables'),
    Food('eggs cups', false, 'Eggs'),
    Food('elbow', false, 'Pasta'),
    Food('elbow macaroni', false, 'Pasta'),
    Food('elderflower', false, 'Flavorings'),
    Food('emmenthal cheese', false, 'Cheese'),
    Food('endive', false, 'Greens'),
    Food('english', false, 'Muffins'),
    Food('english cucumber', false, 'Vegetables'),
    Food('english muffin', false, 'Muffins'),
    Food('english muffins', false, 'Muffins'),
    Food('envelope', false, 'Storage'),
    Food('espresso', false, 'Coffee'),
    Food('espresso powder', false, 'Coffee'),
    Food('essence', false, 'Flavorings'),
    Food('extra large eggs at room', false, 'Eggs'),
    Food('extra sharp white cheddar cheese', false, 'Cheese'),
    Food('extra virgin olive', false, 'Olive Oil'),
    Food('extravirgin olive', false, 'Olive Oil'),
    Food('eye chile pepper', false, 'Peppers'),
    Food('fairy tale eggplant', false, 'Vegetables'),
    Food('farm', false, 'Cheese'),
    Food('favorite burger toppings', false, 'Condiments'),
    Food('fennel', false, 'Vegetables'),
    Food('fennel bulb', false, 'Vegetables'),
    Food('fenugreek', false, 'Spices'),
    Food('feta', false, 'Cheese'),
    Food('feta cheese', false, 'Cheese'),
    Food('fig', false, 'Fruits'),
    Food('figs', false, 'Fruits'),
    Food('fillets', false, 'Seafood'),
    Food('fine', false, 'Salt'),
    Food('fine salt', false, 'Salt'),
    Food('fine sea', false, 'Salt'),
    Food('fine semolina', false, 'Grains'),
    Food('fingerling', false, 'Potatoes'),
    Food('flakes', false, 'Spices'),
    Food('flaky sea', false, 'Salt'),
    Food('flaky sea salt', false, 'Salt'),
    Food('flatbread', false, 'Bread'),
    Food('flax', false, 'Nuts and Seeds'),
    Food('fleur de', false, 'Salt'),
    Food('florets frozen', false, 'Frozen Foods'),
    Food('flour', false, 'Grains'),
    Food('flour tortillas', false, 'Bread'),
    Food('fontina cheese', false, 'Cheese'),
    Food('food coloring', false, 'Condiments'),
    Food('fregola sarda', false, 'Grains'),
    Food('french baguette', false, 'Bread'),
    Food('french bread', false, 'Bread'),
    Food('fresh black', false, 'Pepper'),
    Food('fresh chives', false, 'Herbs'),
    Food('fresh dill', false, 'Herbs'),
    Food('fresh parsley', false, 'Herbs'),
    Food('fromage blanc', false, 'Cheese'),
    Food('frozen artichoke hearts', false, 'Frozen Foods'),
    Food('frozen broccoli florets', false, 'Frozen Foods'),
    Food('frozen butternut squash', false, 'Frozen Foods'),
    Food('frozen dinner', false, 'Frozen Foods'),
    Food('frozen edamame', false, 'Frozen Foods'),
    Food('frozen edamame beans', false, 'Frozen Foods'),
    Food('frozen green', false, 'Frozen Foods'),
    Food('frozen green peas', false, 'Frozen Foods'),
    Food('frozen peas', false, 'Frozen Foods'),
    Food('frozen shrimp', false, 'Frozen Foods'),
    Food('frozen spinach', false, 'Frozen Foods'),
    Food('frozen vegetable', false, 'Frozen Foods'),
    Food('frozen veggie', false, 'Frozen Foods'),
    Food('fruit', false, 'Fruits'),
    Food('furikake', false, 'Condiments'),
    Food('gala apples', false, 'Fruits'),
    Food('garam', false, 'Spices'),
    Food('garlic', false, 'Spices'),
    Food('garlic clove', false, 'Spices'),
    Food('garlic cloves', false, 'Spices'),
    Food('garlic powder', false, 'Spices'),
    Food('garlic salt', false, 'Spices'),
    Food('garnish', false, 'Garnishes'),
    Food('gemelli', false, 'Pasta'),
    Food('generous dash ground cumin', false, 'Spices'),
    Food('ghirardelli cacao bittersweet chocolate', false, 'Chocolate'),
    Food('ghirardelli chocolate', false, 'Chocolate'),
    Food('giardiniera', false, 'Condiments'),
    Food('ginger', false, 'Spices'),
    Food('glazing sugar', false, 'Sweeteners'),
    Food('goat', false, 'Cheese'),
    Food('goat cheese', false, 'Cheese'),
    Food('goathorn peppers', false, 'Peppers'),
    Food('godiva dark chocolate', false, 'Chocolate'),
    Food('golden mountain', false, 'Condiments'),
    Food('golden potatoes', false, 'Potatoes'),
    Food('golden syrup', false, 'Sweeteners'),
    Food('good eating apples', false, 'Fruits'),
    Food('good olive', false, 'Olive Oil'),
    Food('gouda cheese', false, 'Cheese'),
    Food('graham crackers', false, 'Snacks'),
    Food('grainy mustard', false, 'Condiments'),
    Food('granny smith', false, 'Apples'),
    Food('granny smith apples', false, 'Apples'),
    Food('granola', false, 'Cereals'),
    Food('grape', false, 'Fruits'),
    Food('grape tomatoes', false, 'Vegetables'),
    Food('great northern beans', false, 'Legumes'),
    Food('greek yogurt', false, 'Dairy'),
    Food('green apple', false, 'Apples'),
    Food('green beans', false, 'Vegetables'),
    Food('green bell pepper', false, 'Peppers'),
    Food('green cabbage', false, 'Vegetables'),
    Food('green chili peppers', false, 'Peppers'),
    Food('green chilies', false, 'Peppers'),
    Food('green lentils', false, 'Legumes'),
    Food('green olives', false, 'Olives'),
    Food('green onion', false, 'Vegetables'),
    Food('green onions', false, 'Vegetables'),
    Food('green peas', false, 'Vegetables'),
    Food('green sanding sugar', false, 'Sweeteners'),
    Food('greens salad blend', false, 'Greens'),
    Food('grinds black', false, 'Pepper'),
    Food('ground black', false, 'Pepper'),
    Food('ground black pepper', false, 'Pepper'),
    Food('ground cayenne', false, 'Spices'),
    Food('ground cinnamon', false, 'Spices'),
    Food('ground cinnamon for', false, 'Spices'),
    Food('ground flax', false, 'Nuts and Seeds'),
    Food('ground pepper', false, 'Pepper'),
    Food('ground white', false, 'Pepper'),
    Food('gruyere', false, 'Cheese'),
    Food('gruyere cheese', false, 'Cheese'),
    Food('guacamole', false, 'Dips'),
    Food('gyoza', false, 'Frozen Foods'),
    Food('halloumi', false, 'Cheese'),
    Food('haloumi', false, 'Cheese'),
    Food('hamburger', false, 'Meats'),
    Food('hamburger buns', false, 'Bread'),
    Food('handful baby spinach', false, 'Greens'),
    Food('handful cilantro', false, 'Herbs'),
    Food('hanpen', false, 'Frozen Foods'),
    Food('hard eggs', false, 'Eggs'),
    Food('hard peppermint candies', false, 'Candy'),
    Food('hazelnut', false, 'Nuts and Seeds'),
    Food('hazelnuts', false, 'Nuts and Seeds'),
    Food('head belgian endive', false, 'Greens'),
    Food('head boston', false, 'Greens'),
    Food('head boston lettuce', false, 'Greens'),
    Food('head broccoli', false, 'Vegetables'),
    Food('head butter lettuce', false, 'Greens'),
    Food('head cabbage', false, 'Vegetables'),
    Food('head cauliflower', false, 'Vegetables'),
    Food('head escarole', false, 'Greens'),
    Food('head garlic', false, 'Spices'),
    Food('head radicchio', false, 'Greens'),
    Food('head romaine lettuce', false, 'Greens'),
    Food('heavy', false, 'Cream'),
    Food('heavy cream', false, 'Cream'),
    Food('heavy whipping', false, 'Cream'),
    Food('heavy whipping cream', false, 'Cream'),
    Food('hemp', false, 'Nuts and Seeds'),
    Food('hoagie rolls', false, 'Bread'),
    Food('hoisin', false, 'Sauces'),
    Food('hoisin sauce', false, 'Sauces'),
    Food('homemade croutons', false, 'Bread'),
    Food('homemade ranch dressing mix', false, 'Condiments'),
    Food('honey', false, 'Sweeteners'),
    Food('honeycrisp apple', false, 'Apples'),
    Food('hot chili', false, 'Peppers'),
    Food('hot mustard', false, 'Condiments'),
    Food('hot pepper', false, 'Peppers'),
    Food('hot sauce', false, 'Condiments'),
    Food('hot water', false, 'Water'),
    Food('hot wheat cereal', false, 'Grains'),
    Food('hummus', false, 'Dips'),
    Food('ice', false, 'Water'),
    Food('ice water', false, 'Water'),
    Food('iceberg lettuce', false, 'Greens'),
    Food('idaho', false, 'Potatoes'),
    Food('imitation', false, 'Flavorings'),
    Food('inch ginger root', false, 'Spices'),
    Food('inch long piece ginger', false, 'Spices'),
    Food('inches daikon radish', false, 'Vegetables'),
    Food('inner stalk celery', false, 'Vegetables'),
    Food('instant', false, 'Flavorings'),
    Food('instant espresso', false, 'Coffee'),
    Food('instant miso packet', false, 'Soup Mix'),
    Food('irish cream', false, 'Alcohol'),
    Food('italian', false, 'Cheese'),
    Food('italian bread', false, 'Bread'),
    Food('italian herb mix', false, 'Spices'),
    Food('italian rice', false, 'Grains'),
    Food('italian seasoning', false, 'Spices'),
    Food('jalapeno', false, 'Peppers'),
    Food('jalapeno chile', false, 'Peppers'),
    Food('jalapeno pepper', false, 'Peppers'),
    Food('jalapeno peppers', false, 'Peppers'),
    Food('jalapenos', false, 'Peppers'),
    Food('jalape o', false, 'Peppers'),
    Food('jalape o pepper', false, 'Peppers'),
    Food('jamaican', false, 'Spices'),
    Food('japanese eggplant', false, 'Vegetables'),
    Food('japanese powder', false, 'Spices'),
    Food('japanese short grain', false, 'Grains'),
    Food('jasmine', false, 'Rice'),
    Food('jasmine rice', false, 'Rice'),
    Food('juice half a', false, 'Fruits'),
    Food('kalamata', false, 'Olives'),
    Food('kalamata olives', false, 'Olives'),
    Food('kale', false, 'Greens'),
    Food('kewpie', false, 'Condiments'),
    Food('kewpie mayonnaise', false, 'Condiments'),
    Food('kidney beans', false, 'Legumes'),
    Food('king arthur', false, 'Flour'),
    Food('king arthur flour', false, 'Flour'),
    Food('king arthur white wheat', false, 'Flour'),
    Food('kirschwasser', false, 'Alcohol'),
    Food('kobucha squash', false, 'Vegetables'),
    Food('konnyaku', false, 'Noodles'),
    Food('korean rice', false, 'Rice'),
    Food('kosher', false, 'Salt'),
    Food('kosher dill relish', false, 'Condiments'),
    Food('kosher salt', false, 'Salt'),
    // Adding ingredients
  ];
}